using HighJump.Platform.Html.Automation.Tests.Base;
using Xunit.Abstractions;

namespace Korber.EAppTest.MT.MobileApplication.Automation.Tests
{
	public class AutomationTestsBase<tAutomationUser> : AutomationTestsBase<ClientFixture<tAutomationUser>, AutomationFixture<tAutomationUser,PlatformConnection>>
		where tAutomationUser : HighJump.Platform.Integration.Tests.Base.UserCredentials, new()
	{
		public AutomationTestsBase(ClientFixture<tAutomationUser> clientFixture, AutomationFixture<tAutomationUser,PlatformConnection> automation, ITestOutputHelper output)
			: base(clientFixture, automation, output)
		{
		}
	}
}

// This file generated by Accellos MT Generator.
// NVelocity Template used: Accellos.MtGenerator.VelocityTemplates.v3._1._3._0.MobileApplication.Automation.TestsBase.vm
