using HighJump.Platform.Integration.Tests.Base;
using Korber.EAppTest.MT.MobileApplication.Automation.Tests.Users;
using Korber.EAppTest.MT.MobileApplication.Automation.Tests.Utitlities.EnvironmentVariables;
using Mobile.Application.Automation.KorberData;
using MobileApplication.Automation.Common;
using MobileApplication.Automation.Common.DataBase;
using MobileApplication.Automation.KorberRest;
using System;
using System.Linq;

namespace Korber.EAppTest.MT.MobileApplication.Automation.Tests
{
	public class ClientFixture : ClientFixture<SaUser>
	{
	}
	public class ClientFixture<tUser> : ClientFixture<tUser, PlatformConnection> where tUser : UserCredentials, new()
	{
		public KorberCoreRest korberCoreLRest { get; set; }
		private void ConnectKorberApi()
		{
			var sqlTransaction = new SqlServer(new DBInfo
			{
				DataBaseUser = ConfigurationVariable.UserSqlSa,
				DataBaseUserPassword = ConfigurationVariable.UserPasswordSqlSa,
				DataBaseServerName = ConfigurationVariable.DatabaseServerNameKorber,
				DataBaseName = ConfigurationVariable.DatabaseNameKorber
			});
			var request = sqlTransaction.RequestData("Id, PasswordHash",
					$"[{ConfigurationVariable.DatabaseNameKorber}].[dbo].[User]",
					$"LogOnName = '{ConfigurationVariable.UserName}'");
			var userRequest = sqlTransaction.FindRow<DBUser>(request);
			var authenticationTicket = new AuthenticationRest
			{
				UniqueId = new Guid("bcf593b0-7720-4d4e-af75-da2f6b3bd2b3"),  //harcode
				ClientInstanceId = new Guid(),
				UserId = userRequest.ElementAt(0).Id,
				UserPasswordHash = userRequest.ElementAt(0).PasswordHash,
				SessionId = new Guid()
			};
			korberCoreLRest = new KorberCoreRest($"{ConfigurationVariable.KorberProtocol}://{ConfigurationVariable.ServerName}:{ConfigurationVariable.KorberPort}", authenticationTicket);
		}

		public ClientFixture()
		{
						
			ConnectKorberApi();
		}
	}
}

// This file generated by Accellos MT Generator.
// NVelocity Template used: Accellos.MtGenerator.VelocityTemplates.v3._1._5._4.MobileApplication.Automation.ClientFixture.vm
