using System.Net;

namespace Korber.EAppTest.MT.MobileApplication.Automation.Tests
{
	public class PlatformConnection : HighJump.Platform.Integration.Tests.Base.PlatformConnection
	{
		public override string Protocol { get { return "http"; } }
		public override string ServerName { get { return string.Format("{0}:30000", Dns.GetHostEntry("LocalHost").HostName); } }
	}
}

// This file generated by Accellos MT Generator.
// NVelocity Template used: Accellos.MtGenerator.VelocityTemplates.v3._1._3._0.MobileApplication.Automation.PlatformConnection.vm
