using Korber.EAppTest.MT.MobileApplication.Automation.Tests.Utitlities.EnvironmentVariables;

namespace Korber.EAppTest.MT.MobileApplication.Automation.Tests.Users
{
	public class SaUser : HighJump.Platform.Integration.Tests.Base.UserCredentials
	{
		public override string UserName
		{
			get { return "sa"; }
		}

		public override string UserPassword
		{
			get { return ConfigurationVariable.UserPasswordKorberSa; }
		}
	}
}

// This file generated by Accellos MT Generator.
// NVelocity Template used: Accellos.MtGenerator.VelocityTemplates.v3._1._3._0.MobileApplication.Automation.SaUser.vm
