module Korber.EAppTest {

	export class EAppTest extends hj.ApplicationBase {

		public static ApplicationId = "EAppTest";
		public static FileMaintenanceModuleId: string = "FM";

		public static BaseODataEndpoint: string;

		public static ProductInfo: any;

		constructor(private localizedStrings: Korber.EAppTest.Localization.ILocalizedStrings) {
			super(EAppTest.ApplicationId);
		}

		public initialize(): JQueryPromise<void> {
			var result = $.Deferred<void>();
			var product = this.licensingService.getProductById(EAppTest.ApplicationId);
			if (product == null || product == undefined) {
				alert("Unable to location Product Info for: " + EAppTest.ApplicationId)
				result.resolve();
				return result;
			};
			EAppTest.ProductInfo = product;
			if (product.MiddleTierRegistration == null) {
				alert("No MiddleTierRegistration for Product: " + EAppTest.ApplicationId)
				result.resolve();
				return result;
			}
			if (product.MiddleTierRegistration.ODataProvider == null) {
				alert("No OData Provider for registered for Product: " + EAppTest.ApplicationId)
				result.resolve();
				return result;
			}
			var endpointAddress = product.MiddleTierRegistration.ODataProvider.ServiceEndpointAddress;
			if (endpointAddress == null || endpointAddress.length == 0) {
				alert("No OData Endpoint Address specified for Product: " + EAppTest.ApplicationId)
				result.resolve();
				return result;
			}
			EAppTest.BaseODataEndpoint = product.MiddleTierRegistration.ODataProvider.ServiceEndpointAddress;
						result.resolve();
			return result;
		}

		//public buildMenu(root: MenuNode): JQueryPromise<MenuNode> {
		//    var result = $.Deferred();
		//    result.resolve(root);
		//    return result;
		//}
	}
}

hj.System.registerApplication(Korber.EAppTest.EAppTest.ApplicationId, Korber.EAppTest.EAppTest, ["Korber.EAppTest.Localization.ILocalizedStrings"], (configuration) => {
	Korber.EAppTest.Localization.configure(configuration);
});
// This file generated by Accellos MT Generator.
// NVelocity Template used: Accellos.MtGenerator.VelocityTemplates.v3._1._10._2.Mobile.Applicationts.vm
